### ISSUE TITLE
类似 XiaomiMI8Pkg的文件在哪里找？

### ISSUE THREAD

**Issue by sunshinewithmoonlight** [fxsheep/edk2-sagit#1]
你好，
请问这里的XiaomiMI8Pkg 里面的文件在哪里找的吗？
怎么找其他手机的包啊，
就是其他的高通平台，和联发科平台？

**Comment by fxsheep** [comment]
Binary的从XBL提取
源码的参考别人的repo自己写
联发科不用幻想了

**Comment by gesangtome** [comment]
@fxsheep 
你好，我看到在制作UEFI.img的步骤中，有将DTB cat进 uefi.img的尾部，那一个kernel镜像中有多个dtb我要怎么做呢？

**Comment by fxsheep** [comment]
全都append上去就行了，解出来的kernel dtb本来就应该是合在一起的

**Comment by gesangtome** [comment]
@fxsheep 好 我来试一试

**Comment by gesangtome** [comment]
你好，我把我的镜像刷到recovery分区，卡第一屏，你认为是哪里
出现了问题？？
我的镜像的信息如下：
➜  edk2-nx627j git:(0378275) binwalk uefi.img 
DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
0             0x0             Android bootimg, kernel size: 5221424 bytes, kernel addr: 0x0, ramdisk size: 6 bytes, ramdisk addr: 0x1000000, product name: ""
4096          0x1000          gzip compressed data, from Unix, last modified: 2020-04-14 14:04:19
1771039       0x1B061F        Unix path: /dev/block/platform/soc/8804000.sdhci/by-name/vendor
1784487       0x1B3AA7        Unix path: /soc/thermal-zones/cpu-1-7-lowf/trips/cpu17-trip
1835655       0x1C0287        Unix path: /soc/turing_etm0/port/endpoint
2245151       0x22421F        Unix path: /dev/block/platform/soc/8804000.sdhci/by-name/vendor
2258527       0x22765F        Unix path: /soc/thermal-zones/cpu-1-7-lowf/trips/cpu17-trip
2312251       0x23483B        Unix path: /soc/turing_etm0/port/endpoint
2323235       0x237323        Unix path: /soc/qmi-tmd-devices/modem0/modem0_pa
2712365       0x29632D        Unix path: /dev/block/platform/soc/8804000.sdhci/by-name/vendor
2725741       0x29976D        Unix path: /soc/thermal-zones/cpu-1-7-lowf/trips/cpu17-trip
2779465       0x2A6949        Unix path: /soc/turing_etm0/port/endpoint
2790609       0x2A94D1        Unix path: /soc/qmi-tmd-devices/modem0/modem0_pa
3181345       0x308B21        Unix path: /dev/block/platform/soc/8804000.sdhci/by-name/vendor
3194721       0x30BF61        Unix path: /soc/thermal-zones/cpu-1-7-lowf/trips/cpu17-trip
3248445       0x31913D        Unix path: /soc/turing_etm0/port/endpoint
3259429       0x31BC25        Unix path: /soc/qmi-tmd-devices/modem0/modem0_pa
3660515       0x37DAE3        Unix path: /dev/block/platform/soc/8804000.sdhci/by-name/vendor
3673963       0x380F6B        Unix path: /soc/thermal-zones/cpu-1-7-lowf/trips/cpu17-trip
3725131       0x38D74B        Unix path: /soc/turing_etm0/port/endpoint
4132481       0x3F0E81        Unix path: /dev/block/platform/soc/8804000.sdhci/by-name/vendor
4145857       0x3F42C1        Unix path: /soc/thermal-zones/cpu-1-7-lowf/trips/cpu17-trip
4199581       0x40149D        Unix path: /soc/turing_etm0/port/endpoint
4210725       0x404025        Unix path: /soc/qmi-tmd-devices/modem0/modem0_pa
4614301       0x46689D        Unix path: /dev/block/platform/soc/8804000.sdhci/by-name/vendor
4627749       0x469D25        Unix path: /soc/thermal-zones/cpu-1-7-lowf/trips/cpu17-trip
4678917       0x476505        Unix path: /soc/turing_etm0/port/endpoint
5098417       0x4DCBB1        Unix path: /dev/block/platform/soc/8804000.sdhci/by-name/vendor
5111865       0x4E0039        Unix path: /soc/thermal-zones/cpu-1-7-lowf/trips/cpu17-trip
5163033       0x4EC819        Unix path: /soc/turing_etm0/port/endpoint

这是我的仓库地址：https://github.com/gesangtome/edk2-nx627j

**Comment by strongtz** [comment]
大佬好，
我正在尝试在你的repo基础上将edk2移植到小米mix上，现在fastboot boot 已无报错，但屏幕无任何响应
为此我有几个问题想请教一下：
1. MemoryMap中的地址都是根据什么来的？我从xbl中解出了相似的内存地址cfg，是根据那个吗？
2. Framebuffer的地址是否因处理器（机型）而异，需要修改吗？

由于鄙人从前未曾接触edk2及嵌入式开发，所以问题可能显得有点愚蠢，请dalao多多赐教😃

**Comment by fxsheep** [comment]
Memory确实是按cfg来的，不过需要一些调整
framebuffer地址一般不同的soc会有差异，同soc大多数情况下都是一样的，除非OEM改过

**Comment by strongtz** [comment]
(deleted)

**Comment by gesangtome** [comment]
@strongtz  @fxsheep 
你好，你们的XBL为啥能获取到内存区域的cfg呢 ，我自己用工具把XBL和XBL_CONFIG的elf都翻遍了都没找到，还请指点一二

**Comment by strongtz** [comment]
@gesangtome 
我用的是uefitool，可以看到uefiplat.cfg

**Comment by gesangtome** [comment]
@strongtz 我的可以启动了 但是提示 failed to enable mmu ，你有遇到这个问题吗

**Comment by gesangtome** [comment]
@strongtz 谢谢提醒 是查看xbl.elf还是xbl_config.elf呢

**Comment by ghost** [comment]
请问一下各位XBL怎么提取出那些DXE驱动并且把名字自动改为ClockDxe.efi、QcomBds.efi、TrEEDxe.efi等

**Comment by strongtz** [comment]
@gesangtome 我搞的是821平台，所以可能跟你们不大一样，我只有xbl.elf

**Comment by strongtz** [comment]
@RussianEmpireAtChina 我是纯手工做的/滑稽

**Comment by RussianEmpireAtChina** [comment]
@strongtz 你是不是用UEFITool提取的

**Comment by ghost** [comment]
@strongtz 手动改太麻烦了

**Comment by strongtz** [comment]
@RussianEmpireAtChina 自动改我不清楚有什么方法，但我确实是手动改的，因为我也才刚接触

**Comment by ghost** [comment]
@strongtz 啥软件提取的

**Comment by gesangtome** [comment]
@RussianEmpireAtChina 
手动更改$YourDervice.fdf重命名 还有具体的驱动inc里也要改

**Comment by strongtz** [comment]
@RussianEmpireAtChina    uefi-firmware-parser，github上有，但我不建议你用，改名字大概要大半个小时。如果有现成的还是尽量用现成的，我是因为找不到821平台的实在没办法

**Comment by ghost** [comment]
@gesangtome 高通开源edk2的repository能否给个链接，本人也才是刚刚接触这玩意，望多多指教

**Comment by ghost** [comment]
@strongtz 我的手机是Galaxy S10，855平台，找不到现呈的DXE驱动

**Comment by strongtz** [comment]
@RussianEmpireAtChina https://source.codeaurora.org/quic/la/abl/tianocore/edk2
可能是这个？

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/63729574/79348885-2a3a1f80-7f68-11ea-94a7-2c8f982b7427.png)
@strongtz 这玩意有用吗

**Comment by gesangtome** [comment]
@strongtz @RussianEmpireAtChina 
+1就是这个 不过这个很老了 有python问题，改的吐血，最后直接用edk2的mirror

**Comment by gesangtome** [comment]
> @strongtz 我的手机是Galaxy S10，855平台，找不到现呈的DXE驱动

我的是sm8150

**Comment by strongtz** [comment]
我也不太清楚，实话说我现在还只卡在fastboot界面😂

**Comment by gesangtome** [comment]
@strongtz 看看dtb有没有 问题 我刚开始 也卡fastboot

**Comment by ghost** [comment]
我的参照那个一加7的UEFI进去了，但是没有任何驱动

**Comment by ghost** [comment]
就只有一个赤裸裸的EFI Shell，也不能键盘输入

**Comment by gesangtome** [comment]
@RussianEmpireAtChina 
不卡 failed to enable mmu吗

**Comment by RussianEmpireAtChina** [comment]
不啊

**Comment by ghost** [comment]
> @RussianEmpireAtChina
> 不卡 failed to enable mmu吗

不卡住

**Comment by gesangtome** [comment]
@RussianEmpireAtChina 

能否参考一下你的存储库

**Comment by ghost** [comment]
@gesangtome 我直接从那个西班牙大佬clone下来的，基本上没怎么修改直接编译过了

**Comment by gesangtome** [comment]
1+7 ？

**Comment by ghost** [comment]
@gesangtome 是的

**Comment by gesangtome** [comment]
@RussianEmpireAtChina ok

**Comment by ghost** [comment]
@gesangtome 我在网上查到核心部位是QcomPkg/msm8998或者QcomPkg/sdm845，但找不到代码，哪里有下载的

**Comment by gesangtome** [comment]
@RussianEmpireAtChina 
用SDM845

**Comment by gesangtome** [comment]
@fxsheep 
在DeviceMemoryMap.h里，所有的地址都是在System RAM范围内吗？

**Comment by ghost** [comment]
@gesangtome 我知道是sdm845，但是这个QcomPkg的代码库在网上到处找不到，难道这个是高通私有的XBL代码吗？

**Comment by gesangtome** [comment]
@RussianEmpireAtChina 
没错，XBL是私有库 高通开源站的是ABL。

**Comment by ghost** [comment]
@gesangtome 那在哪里搞到这个玩意

**Comment by gesangtome** [comment]
@RussianEmpireAtChina 

不清楚，只能用现成的，我也是直接用的pixel3、sagit和小米8的

**Comment by fxsheep** [comment]
Issues区仅讨论本repo相关的问题，离题内容请移步合适的板块。
