### ISSUE TITLE
请问一下各位XBL怎么提取出那些DXE驱动并且把名字自动改为ClockDxe.efi、QcomBds.efi、TrEEDxe.efi等

### ISSUE THREAD

**Issue by ghost** [fxsheep/edk2-sagit#3]
请问一下各位XBL怎么提取出那些DXE驱动并且把名字自动改为ClockDxe.efi、QcomBds.efi、TrEEDxe.efi等

_Originally posted by @RussianEmpireAtChina in https://github.com/fxsheep/edk2-sagit/issues/1#issuecomment-614063602_

**Comment by ghost** [comment]
有大佬能告诉我用什么软件提取并自动命名，本人新手一枚，望多多指教

**Comment by fxsheep** [comment]
uefi-firmware-parser，别懒了手动来吧

**Comment by ghost** [comment]
看来我要改改uefi-firmware-parser偷个懒了
