### ISSUE TITLE
Build失败了

### ISSUE THREAD

**Issue by redstonee** [fxsheep/edk2-sagit#4]
大佬你好，我按照readme.md里的步骤克隆完了那几个项目，当我执行./build.sh，几秒之后就提示错误，这是怎么回事呀:(
build.py...
/mnt/f/DRIVERS/edk2-sagit/XiaomiMI6Pkg/XiaomiMI6Pkg.dsc(101): error 000E: File/directory not found in workspace
        MdeModulePkg/IntelFrameworkModulePkg/Library/LzmaCustomDecompressLib/LzmaCustomDecompressLib.inf is not found in packages path:
        /mnt/f/DRIVERS/edk2
        /mnt/f/DRIVERS/edk2-platforms
        /mnt/f/DRIVERS/edk2-sagit

- Failed -

**Comment by fxsheep** [comment]
用这个edk2版本
> commit c2f643479eb3f00d930c461cdec3ba420a36072c  

这个edk2-platforms版本

> commit 14d177e378bd34c3e36710db1ff457dcea6da64d

**Comment by redstonee** [comment]
好的我去试试
